### ISSUE TITLE
An environmental issue

### ISSUE THREAD

**Issue by yulong-CSAI** [eureka-research/Eureka#17]
I followed the Git workflow to set up the entire environment and executed this command:
python eureka.py env=shadow_hand sample=16 iteration=2 model=gpt-3.5-turbo  (In order to increase the success rate, a sample size of 16 was set.)

I've received the following log：
[2023-10-26 15:58:07,197][root][INFO] - Iteration 0: Code Run 0 execution error!
[2023-10-26 15:58:07,198][root][INFO] - Iteration 0: Processing Code Run 1
[2023-10-26 15:58:36,157][root][INFO] - Iteration 0: Code Run 1 execution error!
[2023-10-26 15:58:36,157][root][INFO] - Iteration 0: Processing Code Run 2
[2023-10-26 15:59:07,472][root][INFO] - Iteration 0: Code Run 2 execution error!
[2023-10-26 15:59:07,473][root][INFO] - Iteration 0: Processing Code Run 3
[2023-10-26 15:59:40,148][root][INFO] - Iteration 0: Code Run 3 execution error!
[2023-10-26 15:59:40,149][root][INFO] - Iteration 0: Processing Code Run 4
[2023-10-26 16:00:05,806][root][INFO] - Iteration 0: Code Run 4 execution error!
[2023-10-26 16:00:05,806][root][INFO] - Iteration 0: Processing Code Run 5
[2023-10-26 16:00:35,364][root][INFO] - Iteration 0: Code Run 5 execution error!
[2023-10-26 16:00:35,364][root][INFO] - Iteration 0: Processing Code Run 6
[2023-10-26 16:01:05,237][root][INFO] - Iteration 0: Code Run 6 execution error!
[2023-10-26 16:01:05,238][root][INFO] - Iteration 0: Processing Code Run 7
[2023-10-26 16:01:36,413][root][INFO] - Iteration 0: Code Run 7 execution error!
[2023-10-26 16:01:36,414][root][INFO] - Iteration 0: Processing Code Run 8
[2023-10-26 16:02:02,988][root][INFO] - Iteration 0: Code Run 8 execution error!
[2023-10-26 16:02:02,988][root][INFO] - Iteration 0: Processing Code Run 9
[2023-10-26 16:02:30,920][root][INFO] - Iteration 0: Code Run 9 execution error!
[2023-10-26 16:02:30,920][root][INFO] - Iteration 0: Processing Code Run 10
[2023-10-26 16:03:06,019][root][INFO] - Iteration 0: Code Run 10 execution error!
[2023-10-26 16:03:06,020][root][INFO] - Iteration 0: Processing Code Run 11
[2023-10-26 16:03:33,438][root][INFO] - Iteration 0: Code Run 11 execution error!
[2023-10-26 16:03:33,439][root][INFO] - Iteration 0: Processing Code Run 12
[2023-10-26 16:04:02,910][root][INFO] - Iteration 0: Code Run 12 execution error!
[2023-10-26 16:04:02,911][root][INFO] - Iteration 0: Processing Code Run 13
[2023-10-26 16:04:33,260][root][INFO] - Iteration 0: Code Run 13 execution error!
[2023-10-26 16:04:33,260][root][INFO] - Iteration 0: Processing Code Run 14
[2023-10-26 16:05:00,725][root][INFO] - Iteration 0: Code Run 14 execution error!
[2023-10-26 16:05:00,726][root][INFO] - Iteration 0: Processing Code Run 15
[2023-10-26 16:05:32,530][root][INFO] - Iteration 0: Code Run 15 execution error!

When I check each failed log, they all show the same error. Have you encountered this issue before?
Traceback (most recent call last):
  File "/homeb/yulong/Eureka/Eureka-main/eureka/../isaacgymenvs/isaacgymenvs/train.py", line 214, in <module>
    launch_rlg_hydra()
  File "/home/yulong/miniconda3/envs/eureka_v2/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/yulong/miniconda3/envs/eureka_v2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/yulong/miniconda3/envs/eureka_v2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/yulong/miniconda3/envs/eureka_v2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/yulong/miniconda3/envs/eureka_v2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/yulong/miniconda3/envs/eureka_v2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/yulong/miniconda3/envs/eureka_v2/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/yulong/miniconda3/envs/eureka_v2/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/yulong/miniconda3/envs/eureka_v2/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/homeb/yulong/Eureka/Eureka-main/eureka/../isaacgymenvs/isaacgymenvs/train.py", line 203, in launch_rlg_hydra
    statistics = runner.run({
  File "/homeb/yulong/Eureka/Eureka-main/rl_games/rl_games/torch_runner.py", line 124, in run
    self.run_train(args)
  File "/homeb/yulong/Eureka/Eureka-main/rl_games/rl_games/torch_runner.py", line 101, in run_train
    self.agent.train()
  File "/homeb/yulong/Eureka/Eureka-main/rl_games/rl_games/common/a2c_common.py", line 1251, in train
    step_time, play_time, update_time, sum_time, a_losses, c_losses, b_losses, entropies, kls, last_lr, lr_mul = self.train_epoch()
  File "/homeb/yulong/Eureka/Eureka-main/rl_games/rl_games/common/a2c_common.py", line 1115, in train_epoch
    batch_dict = self.play_steps()
  File "/homeb/yulong/Eureka/Eureka-main/rl_games/rl_games/common/a2c_common.py", line 686, in play_steps
    self.obs, rewards, self.dones, infos = self.env_step(res_dict['actions'])
  File "/homeb/yulong/Eureka/Eureka-main/rl_games/rl_games/common/a2c_common.py", line 504, in env_step
    obs, rewards, dones, infos = self.vec_env.step(actions)
  File "/homeb/yulong/Eureka/Eureka-main/isaacgymenvs/isaacgymenvs/utils/rlgames_utils.py", line 256, in step
    return  self.env.step(actions)
  File "/homeb/yulong/Eureka/Eureka-main/isaacgymenvs/isaacgymenvs/tasks/base/vec_task.py", line 355, in step
    self.post_physics_step()
  File "/homeb/yulong/Eureka/Eureka-main/isaacgymenvs/isaacgymenvs/tasks/shadow_handgpt.py", line 653, in post_physics_step
  File "/homeb/yulong/Eureka/Eureka-main/isaacgymenvs/isaacgymenvs/tasks/shadow_handgpt.py", line 370, in compute_reward
AttributeError: 'ShadowHandGPT' object has no attribute 'target_orientation'

**Comment by JKX-yy** [comment]
change to gpt4.0,Can greatly improve the success rate，
![微信图片_20231124170411](https://github.com/eureka-research/Eureka/assets/75010419/b59f311a-f0e8-491c-a43b-0c52f54494bc)

**Comment by MickyFlowers** [comment]
thank you for you reply! But I don't think it has anything to do with whether or not you use gpt3 or gpt4. Please check the output in file eg.`eureka/outputs/eureka/2023-11-14_14-41-48/env_iter4_response4.txt` to see if any other problems occured

**Comment by JKX-yy** [comment]
Yes, I still had a GPT3 success rate of 0 after excluding log errors, and then successfully adopted 4.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eureka-research/Eureka"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 下午5:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eureka-research/Eureka] An environmental issue (Issue #17)





 
thank you for you reply! But I don't think it has anything to do with whether or not you use gpt3 or gpt4. Please check the output in file eg.eureka/outputs/eureka/2023-11-14_14-41-48/env_iter4_response4.txt to see if any other problems occured

**Comment by NextMyLove** [comment]
there are so many error similar to "AttributeError: 'ShadowHandGPT' object has no attribute 'target_orientation'", any solution to solve this problem? I don't know how to solve it ? every error is the "... has no attribute ..."
