### ISSUE TITLE
No module named fbx

### ISSUE THREAD

**Issue by yqi19** [eureka-research/Eureka#27]
Hi, congratulations on your amazing work, when I was trying to install IsaacGymEnvs, I run into the issue that there is no module named fbx, and when I trying to solve it in https://aps.autodesk.com/developer/overview/fbx-sdk it seems that there is no wheel file at all. Then everything gets stuck. Does anyone know why?

Thank you!
```python
(eureka) yu@yu-G470:~/project/Eureka$ python test.py
Importing module 'gym_38' (/home/yu/project/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/yu/project/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
/home/yu/anaconda3/envs/eureka/lib/python3.8/site-packages/torch/utils/cpp_extension.py:28: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import packaging  # type: ignore[attr-defined]
/home/yu/anaconda3/envs/eureka/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/yu/anaconda3/envs/eureka/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
PyTorch version 2.1.1+cu121
Device count 1
/home/yu/project/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/yu/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Emitting ninja build file /home/yu/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
2023-11-19 21:37:46,282 - INFO - logger - logger initialized
<unknown>:3: DeprecationWarning: invalid escape sequence \*
Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbx'
FBX tools must be installed from https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_scripting_with_python_fbx_installing_python_fbx_html
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    envs = isaacgymenvs.make(
  File "/home/yu/project/Eureka/isaacgymenvs/isaacgymenvs/__init__.py", line 29, in make
    env_path = cfg.env_path
AttributeError: 'NoneType' object has no attribute 'env_path'
```

**Comment by NextMyLove** [comment]
same problem

**Comment by NextMyLove** [comment]
I find a solution, which can sovle the fbx'problems. But then I encounter another problem.If you need the solution, please reply.

**Comment by 11whitewater** [comment]
> I find a solution, which can sovle the fbx'problems. But then I encounter another problem.If you need the solution, please reply.

Hi, can you tell me the solution? Thanks!!

**Comment by NextMyLove** [comment]
> > I find a solution, which can sovle the fbx'problems. But then I encounter another problem.If you need the solution, please reply.
> 
> Hi, can you tell me the solution? Thanks!!

it's a pyhton package. you need to find the fbx package whose verison is suitable for you python's version and move fbx's package to your env's lib.
![image](https://github.com/eureka-research/Eureka/assets/87683918/30516cbc-384c-4d34-bfd4-4f9f51d180df)

**Comment by NextMyLove** [comment]
> > I find a solution, which can sovle the fbx'problems. But then I encounter another problem.If you need the solution, please reply.
> 
> Hi, can you tell me the solution? Thanks!!

> > I find a solution, which can sovle the fbx'problems. But then I encounter another problem.If you need the solution, please reply.
> 
> Hi, can you tell me the solution? Thanks!!

你似乎会中文，需要包的话就回复我吧，我qq给你

**Comment by 11whitewater** [comment]
太好了！刚想问你是不是也会中文，您方便留个联系方式吗？我现在添加你~

**Comment by NextMyLove** [comment]
> 太好了！刚想问你是不是也会中文，您方便留个联系方式吗？我现在添加你~

2089494805

**Comment by 1g0rrr** [comment]
I have the same problem. I was able to run joint_monkey.py, but when trying example demo with hands there is this error and I can't install "fbx".
Instruction from Autodesk ask to use some wheel file.
